### ISSUE TITLE
w.cacheControl is not a function after upgrading to v10

### ISSUE THREAD

**Issue by niclimcy** [jeffreylanters/react-unity-webgl#582]
### Please avoid duplicates

- [x] I checked [all open issues](https://github.com/jeffreylanters/react-unity-webgl/issues) and [discussions](https://github.com/jeffreylanters/react-unity-webgl/discussions) and none of them matched my problem.

### Language and Compiler

Other TypeScript compiler

### What environment are you using?

Local Development Server

### When does your problem occur?

While the Unity App is loading

### What does your problem relate to?

The problem seems Unity related

### React-Unity-WebGL Version

10.0.0

### React Version

19.1.0

### Unity Version

6000.0.23f1

### What happened?

After upgrading to v10, my Unity App no longer loads with this log:

```js
unity.js:97 React Unity WebGL: Initializing Unity instance...
vr-showroom.loader.js:1 Uncaught (in promise) TypeError: w.cacheControl is not a function
    at R (vr-showroom.loader.js:1:110686)
    at M (vr-showroom.loader.js:1:112373)
    at vr-showroom.loader.js:1:117359
```

My environment:
- Next.js 14.1 Turbopack Dev
- Next.js static export
- React 19.1

### Would you be interested in contributing a fix?

- [x] yes, I would like to contribute a fix

**Comment by jeffreylanters** [comment]
Hi, thank you for your report! I'm onto it!

**Comment by niclimcy** [comment]
> Hi, I've pushed version v10.1.1 which should resolve this issue. Please let me know if this works for you. Thanks for submitting an issue so quickly!

It works great now, thanks!
